INSERT INTO role VALUES (1,'ROLE_ADMIN'), (2,'ROLE_CUSTOMER') ON CONFLICT DO NOTHING;

INSERT INTO booking_status VALUES ('PENDING'),('PICKED_UP'),('RETURNED'),('EXTENDED'),('CANCELLED') ON CONFLICT DO NOTHING;

INSERT INTO all_users (id,password,username,role_id) VALUES (3,'$2a$10$Ih1WSBE8.7qF2bhyhPs83OuYjHhX5twEZ97pwPZJXXHi94vwLaYgq','Dilrukshi',1) ON CONFLICT DO NOTHING;

INSERT INTO admin (admin_id,username,password,user_id,email,contact_no) VALUES (1,'Dilrukshi','dilly',3,'dilly@gmail.com','234 432 3456') ON CONFLICT DO NOTHING;

INSERT INTO additional_equipment (equipment_id,equipment_name,index,img_link,description,type,ae_rental_price) VALUES (2,'LuvLap Infant Baby Car Seat Cum Carry Cot With Rocker And Canopy - Dark Blue',0,'https://cdn.fcglcdn.com/brainbees/images/products/438x531/795073a.jpg','Age - 0 to 15 Months, Material - HDPE Fabric ( 100% polyester) Sponge, Safety Harness - 3 Points, Adjustable Canopy - Yes, Side Impact Protection - Yes, Carry Handle - Yes, Installation System - Seat Belt, Car seat over all dimension - 65 x 38 x 52 cm, Seat dimension - 26 x 22 cm, Reversible handle width - 36 cm, Product weight - 3.4 kg, Carrying capacity - 13 kg','Baby Car Seat Cum Carry Cot',50),
                                                                                                         (3,'SLIMLINE SAT NAV, (7 INCH) with 2020 WORLD MAPS EDITION',1,'https://images-na.ssl-images-amazon.com/images/I/61NDRJIEaWL._AC_SX679_.jpg','GPS Navigation for Car Truck Motorhome, Features Postcodes, Speed Cam Alerts, Lane Guidance & POI, latest touchscreen technology, no need for styluses, HD display providing clearer viewing for poor eyesight, can be seen in bright sun light','Satellite navigation Device',75),
                                                                                                         (4,'LuvLap Baby Backless Booster Car Seat - Black',2,'https://cdn.fcglcdn.com/brainbees/images/products/438x531/1368707a.jpg','Age - 6 to 12 Years, Padded armrests, Overall Dimension - 44 x 40 x 22 cm, Seat Dimension - 33 x 22 cm, Product Net Weight - 1.35 kg, Carry Capacity - 15 to 36 kg','Backless Booster Car Seat',50),
                                                                                                         (5,'XGODY 712 SAT NAV GPS Navigation System 7 Inch',3,'https://images-na.ssl-images-amazon.com/images/I/71vo3fI5nsL._AC_SX679_.jpg','8GB 256MB Car Truck Lorry Satellite Navigator with Post Code Search Speed Camera Alerts, ','Sattellite Navigation Device',30),
                                                                                                         (6,'Cooper Cooler Rapid Beverage & Wine Chiller, Silver',4,'https://images-na.ssl-images-amazon.com/images/I/41CwrBe9TGL.jpg','chills cans in 1 minute and wine bottles in 6 minutes, heats baby bottles, Measures approximately 16 by 10-1/2 by 8 inches','Beverage Chiller',80) ON CONFLICT DO NOTHING;